# Example file for controlling loading image and overlay text display
# To activate remove "_example" from filename
# ---------------------------------------------------------------------------------------
# Note: Specify filenames without extension (.jpg will be added internally)
# ---------------------------------------------------------------------------------------

# Overlay title
Title: <b><#0077FF>Reforged Eden 1.8</color></b> <size=65%><#ffffff>(Build 36)</color></size>

# Overlay body (typically multi-line text)
# If commented out, only the title will be displayed
Body: |
  <size=135%><#ffffff><b>October 2:</b></color></size>
  <size=85%>- Fusion reactor and shield chargers and capacitors no longer show particles/animations when there's no power.
  - Added new model for Science station thanks to Vertex Rage Studio.
  - Fixed missing localization updates and missing PDA parameter errors.
  NOTE for singleplayer: if you want the updated PDA fixes you will need to deactivate any currently active mission and use the <#ffff00>pda readdata</color> console command to refresh your PDA. <#ff0000>This may reset your mission progress!</color>
  
  <size=135%><#ffffff><b>November 13:</b></color></size>
  <size=85%>- <#ffff00>HOTFIX: Tentative fix for ice moons crashing game.</color> (No build change)
  
  
  <#FFFFFF><i>Fully exit the game when changing saves or servers to prevent issues.</i>
  <#FFFFFF><b>Please do not report issues to the game developers unless you can reproduce it in a default, unmodified save game.</b></color>

# To show a certain image at the start of each loading image sequence, specify the respective file name
# To use the default random image selection, comment out the following line
# FirstPic: p05

# To show the overlay text with certain images only, specify the respective file names
# To show the text with every image, comment out the following line
# ShowWith: [ p02, p03 ]

# Show time for images - if not specified differently below
# If commented out, the default is 10 seconds
# Note: This time depends on the speed of the client computer as when loading a game a lot of work is done in parallel
StandardShowTime: 15

# To set a specific show time for certain images, specify "filename: time" lines
# If not needed, comment out all lines of the following parameter
ShowTimes:
  # p05: 6
  # p06: 8
